secret:
    enabled: ENC[AES256_GCM,data:dlO8iw==,iv:6MLMeyMWpZje7nYl9MhlHyAPV0mXi7S/5jUbw3Bs/tA=,tag:wiqiR71v4aKDkAUslsaDDg==,type:bool]
    additionalLabels: null
    annotations: null
    files:
        - nameSuffix: ENC[AES256_GCM,data:XOE=,iv:z0xwYhWL2xQMITprkfzkaLm2cZALeqAS3sbSjh65W/k=,tag:zhJ2c4AwuDgBEvH4SOvlSA==,type:str]
          data:
            DB_HOST: ENC[AES256_GCM,data:Di0mfCHJta3hSsk51e+biguT9zoa8mPhQmtuz1MLXA/XFtNOfffs7OSN57D8owhVwjRWx64DRkXDVsVRXVzgcyWPYgQ=,iv:tTG8nXC61lWal92PYHznr9NwTcjhA72PmtM71i7sZ+A=,tag:lEfmFpY8tkz7IdSmKcKSdg==,type:str]
            DB_NAME: ENC[AES256_GCM,data:+i7klyisVZKZgyQLomh8,iv:+SRiRQQ7OTiio8mJI44rTss1hc4bYoEfrUwoEp6ME3c=,tag:UdmWqgBqTdEd/AEX/MJdcg==,type:str]
            DB_PASS: ENC[AES256_GCM,data:RP9imC0sNaddJkXMpGlAGk8XoJM=,iv:gqar/tlfCZcvwHk8EY9P7Ejai4ZbKmNcPNFVD4S/Vds=,tag:/dEp/eFduXHAG/z2GhiUnQ==,type:str]
            DB_USER: ENC[AES256_GCM,data:B+/ufw==,iv:NU7FyXW9Qutwu6jnnfsNJ8pmgf/aLipvqkriMwag5OE=,tag:aWlzBN/o2HMrMa1/KRN1XA==,type:str]
            DCC_KEY: ENC[AES256_GCM,data:rhPYuKMh4+tGeKfK5x+WeQ==,iv:eQOzWi4NGqKi46K+/Njrf22JtbltkJ49vwr3jQebGD0=,tag:eCsHgCAPxSr3NWef2N+XzQ==,type:str]
            DCC_SECRET: ENC[AES256_GCM,data:K3n3pKls34f10WqDXtBK1xFr383AKeQr9iQ=,iv:6X3LfFmUqizeyYC4Oo18/GZj+fqIZd31tWh8rZEfFnA=,tag:X/G70ZEU5xulAyYK/94OvQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-af1-uat-app-secrets
          created_at: "2026-03-13T12:08:00Z"
          enc: AQICAHgEJiafceW3D0va99MIn9sancffrAKAY84D33DCdRx32QESjOdRwzoFPG6UHSw1Wer1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBQEpHlxF/4uMOK0QAgEQgDuCFr8KIxmMS//ihgX/pr89VwLA4BJ47Zrr3J+i0DRpkfFTSUXHaVsY3udIEQqJ0uwlh5P0y2J7KdNd1w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-13T12:08:01Z"
    mac: ENC[AES256_GCM,data:up2JKOK8W1q/0ujFqqyX5WYb370cnMEKvOYcgNuJlrm9G8WnwiLnLX81AXdJRLpjpmyFA84vG6VLD1xx5TY39yyKRJQVsjOh6j4INMY73MJHnZRjH9n9FYW3jVXDsHhudnNmHtKNqNewS66S0QwkLn3gYM/LMtTpkEqiVleklXg=,iv:H/GaLRcqvmx6rX+zT0BVOycNIQT63NlwRXPdwfXICOY=,tag:kH1OBad3IPEaXkHMdOu/2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
