secret:
    enabled: ENC[AES256_GCM,data:SFtBaA==,iv:9Oe51kJzU3q/DzKWMzYXqTiBCEduwgYWgzrwVvj6TvQ=,tag:VO1WG1ak8wnYztz3d6XUCA==,type:bool]
    additionalLabels: null
    #ENC[AES256_GCM,data:R1KO10CNbvkUPbg=,iv:WWttgFVzuQzHYawBlEj/F269rJ7KLZUo6dxFVxyl7bc=,tag:59oz+c9NuJkxDqrjzQxpbw==,type:comment]
    annotations: null
    #ENC[AES256_GCM,data:jPpUsGUPsMc9Xdo=,iv:dMlbflTsRA8Zr/JtNrVQuv9e3fn0vPVxni38qazmp9Q=,tag:YknWNDnFT31vw1U+NgQhRQ==,type:comment]
    files:
        - nameSuffix: ENC[AES256_GCM,data:ARrFSB4t,iv:Q35z0+n18j52qzvQrYD64DMG/TAJ22kR45/U/zCp6tA=,tag:P/8ZC+3FdBVq1f2/04rc2g==,type:str]
          data:
            env: ENC[AES256_GCM,data:ceqe2lC6veYoTWBSyHXRpxT5mh5E3nwEebZUxTFJ/VEJr4a4E/zpHL9GPNlXm4ZFt45CnCA9XA5y8iiP/poWg4jNQboznCtzLesQ4glD7UnxyGgSs5Ymepazo9qAbMnVvCz1JbsdW+6b9K9QpR5c0znTiLwOTdZaI7gT1dzfgtyTe/bZzUxN1uIvS0Ezs5U1rwDIeTG3+cYjatIISEBvr+o/ok7scfGy9zVUlK2tDnBsx80vRrGJy4YgYmkH6HjmiK7fFR/JExu9Iy8EG52Q/g0ykiOIt9dMvtqsMIK/dPOcyN3IMB1RKcJrMubKUfjPtBg9dYqvzBOrEEqLBDY4anDffW4bbs8xovMGJw8tMUfCVQoItf5omLiDX9WsxRo8kUoy05PjhqTpBfGLOGRCIFoI+xw2ZSyrIhYNtqfV+tsIuThGpUIMA+J5BbeB++qUJ/xELPXuedKsFk6Qrop56TaKdAQj,iv:nGro9V5UM5bR15soPOsIzevxW6cdR3r1dDizzlSf5Lw=,tag:0+bCkb+l5crDY47LlYpMLA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-af1-uat-app-secrets
          created_at: "2026-03-13T12:09:46Z"
          enc: AQICAHgEJiafceW3D0va99MIn9sancffrAKAY84D33DCdRx32QHLK9b6gdMOrBxpOykLH1/+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzhulu+Gqg/SoGYEkAgEQgDvhGRcr/e/mbTDReu53f/BiUd6dXvxih6K62jCnZpyxI/cxjiFXyAu22O3BkgKeKCVJFhVTvpFU/dRYBA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-13T12:09:47Z"
    mac: ENC[AES256_GCM,data:qdy1nq9WLewd7shAK5uDuKAijK6jmCoJj6/I4KWC/8oo7RUD/5VqMA/ZMZq2/8inwdaoTbSwYTqNW/ZOEWxIO0Ij6vawhzA9dItznF1K2DY2h+UwBth/aXW6ded8HUB4A72lC1wlZQMekQj1JyNrNAmMocy5/CrqyVbrtdjjgU8=,iv:KC5yfXg/0syadTlql4+yVYzgjSDbJLdgwwXpiVN1Kog=,tag:4FLjlCsxitPtJHzMLYZcew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
