secret:
    enabled: ENC[AES256_GCM,data:Gt9A6w==,iv:b2ge6lhArIiDMduoGUEBIZpBU6onvuwHeI0NgVuiCYU=,tag:J3XTJtno58NMwEo80QppEQ==,type:bool]
    additionalLabels: null
    #ENC[AES256_GCM,data:cxMV1dyfnF09Bwg=,iv:nKdSEPaUzF1STOHJzn3MPWX108/QhyRrjiG+R2XyK0s=,tag:p6gdyr45JGIDKzfpbDJleg==,type:comment]
    annotations: null
    #ENC[AES256_GCM,data:Q/JYpCJZyigSeFs=,iv:kBxs1+q43iHO588KzQPg4InBvMEeLdO3YnPugpbU+Jo=,tag:5lSaN1PQLPkIClh0wfx6Ag==,type:comment]
    files:
        - nameSuffix: ENC[AES256_GCM,data:sMx7TEqQ,iv:cu7Dl9PD7qOBR4ByMSBhaAxs9h+NomNp00oTSILeUa0=,tag:/Nxlp+XL7Oj8LJYrKGjjdw==,type:str]
          data:
            env: ENC[AES256_GCM,data:+pa2XO7+ubOsOBmQV912PgcrtC/RjJcKwzHP9kiylu86jNye3VFMf4Q52b3B+9lOgn5OpUzrscHQE/Vok6ziMEFZEjiz/DBQjU82W8W8CUjHOVOJW4ePTmogJlj41j2r4+9LedntihZGNBeSCKEWD7z0jsUyFf9sYrDy8qDE54MyRvlk5Ne//0c4pawM4pyKiae6sWCdKxdWQCkYHytfold9qohqRKfQgO+guq0Tqecw/PmL6DiO69YnpTq7A/vFC5hQs8rDqGGXyFIWl8CDNcHe5G9kzqeuXO1VcMO7BPTnIt3IlzjH9Zk5Tj3LPjzWCd2B+5f0n4zyAlRRBBR2ZccHErl9nnbm1A0kCMqCxXf9ReyVnOwpzluuXFF9sQs+/eIqYUj6bHXXWTpFbM1gAq326+ikj0qoTba1O/JuAtj3hKmD59xQq1LvTn4aDd0uRoPwwE7fmGwWi69KrWguyeABy4SRzlWNCs5zVw==,iv:GajGDPfDuzdSUdhxKYlf+wqeAB4Su/9MHV7+PWulVyQ=,tag:iUWcSvPIUTUXXTv6wgWnVg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-af1-uat-app-secrets
          created_at: "2026-03-13T12:57:40Z"
          enc: AQICAHgEJiafceW3D0va99MIn9sancffrAKAY84D33DCdRx32QGks4bMCvq5N19kGEoDhY8lAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgiNXKds0sGm8INWXAgEQgDuBQ90NteTfccQGj1tQ+m2ZKvWmq9hY0IsqW4BJBvlUdPyFg6TtF5KUN0Ydtuu6SR3gzgcXehnEpuoUAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-13T12:57:40Z"
    mac: ENC[AES256_GCM,data:sMlBRmQI8Zg8cPhOFb1veaN+m5lhtw+ZKxrY1+q9gHOWmFqJrknt7RV2nDOGUEwnnioR1NOVKSchRZsCfIQ3x0z0cGX3/ZSDOh7ld8lvXSUnUtzka8bd13QbAWS1amTzhpF3VjEGdUMj07kSc7RXyz3P1qiyezM/oVUnMxzDYDU=,iv:Ge+q/UuEIV5ZLkKWoaB4RKC5mKbeKN5WZ0jbxX8IyXQ=,tag:rpJUa6Lipx6bplumQUJZkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
