{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
{{ include "application.labels" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.deployment.additionalLabels }}
{{ toYaml .Values.deployment.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        {{- if .Values.cronjob.podAnnotations }}
        metadata:
          annotations:
          {{- with .Values.cronjob.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        spec:
          {{- with .Values.cronjob.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ template "application.name" . }}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              {{- if .Values.cronjob.command }}
              command:
                {{-  range .Values.cronjob.command }}
                - {{ . }}
                {{- end }}
              {{- end }}
              env:
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              {{- if .Values.cronjob.env }}
              {{- range $k, $v := .Values.cronjob.env }}
              - name: {{ $k }}
                value: {{ $v }}
              {{- end }}
              {{- end }}
              {{- if .Values.cronjob.envFrom }}
              envFrom:
              {{- range .Values.cronjob.envFrom }}
              {{- if (eq .type "configmap") }}
              - configMapRef:
                  {{- if .name }}
                  name: {{ .name }}
                  {{- else }}
                  name: {{ template "application.name" $ }}
                  {{- end }}
              {{- end }}
              {{- if (eq .type "secret") }}
              - secretRef:
                  {{- if eq .nameSuffix ""  }}
                  name: {{ .name }}
                  {{- else }}
                  name: {{ template "application.name" $ }}-{{ .nameSuffix }}
                  {{- end }}
              {{- end }}
              {{- end }}
              {{- end }}
              {{- with .Values.cronjob.command }}
              command:
              {{- range . }}
                - {{ . | quote }}
              {{- end }}
              {{- end }}
              {{- with .Values.cronjob.baseArgs }}
              args:
              {{- range . }}
                - {{ . | quote }}
              {{- end }}
              {{- end }}
              {{- with .Values.cronjob.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
{{- end }}