{{ if not .Values.application.enabled }}
{{- if .Values.service.enabled }}
{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "application.labels.plain" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.service.additionalLabels }}
{{ toYaml .Values.service.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.port }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
{{ include "application.labels.selector" . | indent 4 }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}