secret:
    enabled: ENC[AES256_GCM,data:B/HlFA==,iv:WYhN7m8eQWOJRqN+QS1N8B2sjoFpiHwJglp+gqYQUKw=,tag:bYhQyrYuZ28znHT82QN2RQ==,type:bool]
    additionalLabels: null
    annotations: null
    files:
        - nameSuffix: ENC[AES256_GCM,data:u8GZ1dO4,iv:ZLATeQoRAWIYvzlN/hoqVtQ/B3AOc1ogbMnFJsacCu8=,tag:YtIP8OTvbPwKq0Quj0wE/Q==,type:str]
          data:
            env: ENC[AES256_GCM,data:J6VqMAbZ/F3dw8hcogJXb9E5f1hVGwlK0+1vopGqIn+tXKfR+AT5Lq6bDN8tjEqZuHxU7Wix1vXmTVbWmtMb5KeN/JBurWFvYzqdS33g6dttXwaLblVWySt9JJqqgxzy93pDDC3+E3ZCDk6qYydwsoNMyFbIN3gpt8RSyVBKeevKKpecW9sTnoCQXn+/DGUoG9lxyJ10RvCH42aKjjL4Ze2wLn7NStiohnTbH7lGcxyn0W/XG4j+NLDs4VxJ5ErNqkGNn3crNn8erTlteCctQc4HfF6rT481vws4EzF97/3GqFNHtPEUEIGMOzx4lSXMxjhV7fr5I41EGJIRtGZFAUZNawmfPTruEv2zuzFM131n8FsIR93wTEZB8B/pk3X7PoeHDQV93jU0snu8jYYVxwqtHJpAPDRX+lOgyIzuC3lqzSZQ4pWI3tX5+dHOriraeq097xaxo7L5NQB/YCEfQxhsaxDSX103eKmaXp3waQSTMY3N/fV1ujdvpm25vb3tmAyl3Tskpe3+XRTn2bOZtRik+85DpLuiz6sEhZvrtGFMX3KIEJDivDDHRg9vDHIh6UM0H6qWYeIXcuFPD48O4UYwwSiMp1DfyVNoHZA8tTF8/LVZRn1bfPHUHrGNEmgzggWrs9E2DCs46/6XdZmJKdm0y5+zyEpEZhnrpZa5QScAepE5+++vznAdPthZVfC5SMu4KWqB9k+nAIA7ytaP26AF3GO6NwlLAxoy/I6aQOTwkryF70Y+qbARXk4G9C11oemOELYIQiJHNn4im2yQpY23e4ZWyc/wD5ZZCct6JibNSg0VQwetfWYJt4KoszhXCmMeg8cR/w892m+gA6tWvhpsoQVl9188aul37NOTIb+P2AXmdL8FV8ODJ4jApwqIryyek3o+l2cwvwWxzLPpOFXjE/TGi/Jq9RXsiwmysUKKw42EUMcayyqW8tqfbhgqgkWbb/2214vvKjQRZYzpB6jJaTl2Ezj2g1m7+4BVBpNozntJ3GbZBtf7ndz4IqrHJxRXnDPFgB9t5HSdCBmDiTTW0sYnDlmAyFw7AvE9Klc/LD54dBbN4mlOVPrmG+4OdDyD9wF2edcjkX9RMeo3CHvkY9o6swio0BOUzFBzwhXXNL8QoNWkzIMVdhlcWZ9lMcj/lrMA5LZicQ==,iv:w8rcDMyMIia9/ZnFfIRL0iF/BpqlEJfDKtTmwNHB/1I=,tag:TW9UAjoH5pBuWtrDBzh+jg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-af1-uat-app-secrets
          created_at: "2026-03-13T12:09:32Z"
          enc: AQICAHgEJiafceW3D0va99MIn9sancffrAKAY84D33DCdRx32QHgQN0oNAb/ZNRR1WvKxW5IAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvXz772S8OS4CwrG+AgEQgDvgfZtWoq/X3ls741VhjzD+sS+WbgVj8tAlZj28KFxWo/1bK4xxislXFnuZllslgb7Ekq7yWa1U0r7uow==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-13T12:09:33Z"
    mac: ENC[AES256_GCM,data:SenixOOqh2lTdPc+N0PEXmgkf/KJ23gBwROR2MbjjeYHvJu6J7k5oP5capYerCiexMDaHGpLgHrHNjwm2s6yhMd1vNVMCwoPOnoBB7n254gd3uX3zdU6fPEPXG91VhuzRbMm0edP7MryE2q50bA4uyw8mNYFQ7e01ijOctKPqeQ=,iv:5zL1U/H2z1kwZnbU/Pa2f2yren8bl1glXl2tzwRUKe8=,tag:0TMCRRhEJGmiwHsrhik7ww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
