# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
resource "random_password" "master" {
  length  = 20
  special = false
}

output "password" {
  value = random_password.master.result
  sensitive = true
}
