# Name of the application.
applicationName: "checkout"
environment: uat
#tier: frontend

# These labels will be added on all resources, and you can add additional labels from below on individual resource
labels:
  group: paydart-generic-helm
deployment:
  enabled: true
  # By default deploymentStrategy is set to rollingUpdate
  # You can change type to `Recreate` or can uncomment `rollingUpdate` specification and adjust them to your usage.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  # Select nodes to deploy which matches the following labels
  nodeSelector:
    frontend: "true"
  # cloud.google.com/gke-nodepool: default-pool

  # If needed to setup host aliases
  hostAliases:
  # - ip: "127.0.0.1"
  #   hostnames:
  #   - "foo.local"
  #   - "bar.local"

  # Init containers which runs before the app container
  initContainers:
  # - name: init-contaner
  #   image: busybox
  #   imagePullPolicy: IfNotPresent
  #   command: ['/bin/sh']

  # Additional labels for Deployment
  additionalLabels:
  # key: value

  # Additional label added on pod which is used in Service's Label Selector
  podLabels:
    tags.datadoghq.com/env: uat
    tags.datadoghq.com/service: checkout

  # Pod Annotations on deployments for OT
  podAnnotations:
    # instrumentation.opentelemetry.io/inject-php: "true"
    # instrumentation.opentelemetry.io/container-names: "app"
    admission.datadoghq.com/enabled: "true"
    ad.datadoghq.com/checkout.logs: '[{"source":"nginx","service":"checkout"}]'
    sidecar.istio.io/inject: "false"
    ad.datadoghq.com/checkout.check_names: '["php_fpm", "nginx"]'
    ad.datadoghq.com/checkout.init_configs: "[{}, {}]"
    ad.datadoghq.com/checkout.instances: |
      [
        {
          "status_url": "http://%%host%%/fpm-status",
          "ping_url": "http://%%host%%/fpm-ping",
          "use_fastcgi": false,
          "ping_reply": "pong"
        },
        {
          "nginx_status_url": "http://%%host%%/nginx_statu/"
        }
      ]

  # Annotations on deployments
  annotations:

  # Additional Pod Annotations added on pod created by this Deployment
  additionalPodAnnotations:
  # key: value

  # Replicas to be created
  replicas: 1

  # Revision History Limit for Replica Sets
  revisionHistoryLimit: 4

  # Secrets used to pull image
  imagePullSecrets: "docker-hub"

  # If want to mount Envs from configmap or secret
  envFrom:
  # - type: configmap
  #   name: my-configmap
  #  - type: secret
  #    name: ""
  #    nameSuffix: db
  #Only one choice is valid: either nameSuffix or name

  # Environment variables to be passed to the app container
  env:
    - name: DD_VERSION
      value: "123456"
    - name: DD_ENV
      value: prod
    - name: DD_PROFILING_ENABLED
      value: "true"
    - name: DD_SERVICE
      value: checkout
    - name: DD_RUNTIME_METRICS_ENABLED
      value: "true"
    - name: DD_TRACE_CLI_ENABLED
      value: "true"
    - name: DD_TRACE_CODEIGNITER_ENABLED
      value: "true"
    - name: DD_LOGS_INJECTION
      value: "true"
    - name: DD_TRACE_CODEIGNITER_ANALYTICS_ENABLED
      value: "true"
    - name: DD_TRACE_SAMPLE_RATE
      value: "1"
    - name: DD_AGENT_HOST
      value: "datadog-agent.datadog"

  # - name: OTEL_PHP_AUTOLOAD_ENABLED
  #   value: "true"
  # - name: OTEL_SERVICE_NAME
  #   value: "checkout"
  # - name: OTEL_TRACES_EXPORTER
  #   value: "otlp"
  # - name: OTEL_EXPORTER_OTLP_PROTOCOL
  #   value: "grpc"
  # - name: OTEL_EXPORTER_OTLP_ENDPOINT
  #   value: "http://otel-collector:4317"
  # - name: OTEL_PROPAGATORS
  #   value: "baggage,tracecontex"

  # Volumes to be added to the pod
  volumes:
    - name: env
      secret:
        secretName: checkout-config
        defaultMode: 420
        optional: false

  # - name: configmap-volume
  #   configMap:
  #     name: '{{ template "application.name" . }}-configmap-nameSuffix'
  # - name: secret-volume
  #   secret:
  #     secretName: secret-name
  # - name: volume-name
  #   emptyDir: {}
  # - name: persistent-volume-name
  #   persistentVolumeClaim:
  #     claimName: claim-name

  # Mount path for Volumes
  volumeMounts:
    - mountPath: /var/www/html/checkout/.env
      name: env
      readOnly: true
      subPath: env

  # Taint tolerations for nodes
  tolerations:
    - effect: NoSchedule
      key: workload
      operator: Equal
      value: frontend
  # - key: "dedicated"
  #   operator: "Equal"
  #   value: "app"
  #   effect: "NoSchedule"

  # Pod affinity and pod anti-affinity allow you to specify rules about how pods should be placed relative to other pods.
  affinity:
  #  nodeAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #      - matchExpressions:
  #        - key: disktype
  #          operator: In
  #          values:
  #          - ssd

  # Image of the app container
  image:
    repository: pdsrvcprovider/checkout
    tag: "buildn-602"
    pullPolicy: IfNotPresent
    appprefix:
      enabled: true

  command: []
  baseArgs: []

  # command: ["sleep"]
  # baseArgs: ["infinity"]

  # Container Security Context
  containerSecurityContext:
    privileged: true
    # allowPrivilegeEscalation: false
    # capabilities:
    #   drop:
    #     - ALL
    #   add:
    #     - NET_BIND_SERVICE
    #     - SETGID
    #     - SETUID
    capabilities:
      add:
        - ALL

  # Pod Security Context
  securityContext:
    []
    # runAsNonRoot: true # TODO Move All Docker to run as normal user
    # fsGroup: 33
    # runAsUser: 33
    # runAsGroup: 33
    # fsGroupChangePolicy: "OnRootMismatch"
    # sysctls:
    # - name: net.ipv4.ip_unprivileged_port_start
    #   value: "0"

  service:
    port:
      - name: web
        containerPort: 8080
        protocol: TCP

  livenessProbe:
    httpGet:
      scheme: HTTP
      path: /checkout/health
      port: web
    initialDelaySeconds: 60
    periodSeconds: 10
  readinessProbe:
    httpGet:
      scheme: HTTP
      path: /checkout/health
      port: web
    initialDelaySeconds: 30

  # Resources to be defined for pod
  resources:
    limits:
      memory: 1Gi
      cpu: 900m
    requests:
      memory: 256Mi
      cpu: 300m

  # Add additional containers besides init and app containers
  additionalContainers:
  # - name: sidecar-contaner
  #   image: busybox
  #   imagePullPolicy: IfNotPresent
  #   command: ['/bin/sh']

# Add Storage volumes to the pods
persistence:
  enabled: false
  mountPVC: false
  mountPath: "/"
  accessMode: ReadWriteOnce
  ## If defined, storageClass: <storageClass>
  ## If set to "-", storageClass: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClass spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  additionalLabels:
  # key: "value"
  annotations:
  #  "helm.sh/resource-policy": keep
  storageSize: 8Gi

# Service object for servicing pods
service:
  enabled: true
  type: ClusterIP
  port:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: web
    # - port: 8081
    #   targetPort: http-metric
    #   protocol: TCP
    #   name: http
  multiServices:
    enabled: false
    #### Example ####
    # port:
    #   - port: 8082
    #     targetPort: http-admin
    #     protocol: TCP
    #     name: admin

# Ingress object for exposing services
ingress:
  enabled: true
  #The load balancer name and group name should be the same across all application Helm files
  loadbalancername: global
  groupname: generic
  awssubnets: "subnet-0c5198bc59d798f66, subnet-0f1a89c21157f9b3a, subnet-0cb93dd6a6dbad6cd"
  wafarn: ""

  ingressClassName: alb
  # Port of the service that serves pods
  servicePort: 80

  # List of host addresses to be exposed by this Ingress
  hosts:
    - host: uat-checkout.gtipayglobal.com
      paths:
        - path: /
          pathType: Prefix
          redirect: false

  # Add annotations to this Ingress
  annotations:
    # nginx.ingress.kubernetes.io/affinity: cookie
    # nginx.ingress.kubernetes.io/session-cookie-path: /
    # nginx.ingress.kubernetes.io/use-regex: 'true'
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: '180'
    # nginx.ingress.kubernetes.io/proxy-read-timeout: '180'
    # nginx.ingress.kubernetes.io/proxy-send-timeout: '180'
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]' #'[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=240
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400, load_balancing.algorithm.type=least_outstanding_requests
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /checkout/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/actions.redirect-to-www: >
      {"Type":"redirect","RedirectConfig":{"Host":"#{host}","Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_302"}}

# Role Based Access Control
rbac:
  enabled: true

  # Service Account to use by pods
  serviceAccount:
    enabled: false
    name: ""

  terrafrom_serviceAccount:
    created: true

    # Additional Labels on service account
    additionalLabels:
    # key: value

    # Annotations on service account
    annotations:
    # key: value

  existingRoles:
  # - name: springboot

  # Create Roles (Namespaced)
  roles:
  # - name: configmaps
  #   rules:
  #   - apiGroups:
  #     - ""
  #     resources:
  #     - configmaps
  #     verbs:
  #     - get
  # - name: secrets
  #   rules:
  #   - apiGroups:
  #     - ""
  #     resources:
  #     - secrets
  #     verbs:
  #     - get

  existingClusterroles:
  # - name: springboot
  # Create ClusterRoles (Clusterwide)
  clusterroles:
  # - name: configmaps
  #   rules:
  #   - apiGroups:
  #     - ""
  #     resources:
  #     - configmaps
  #     verbs:
  #     - get
  # - name: pods
  #   rules:
  #   - apiGroups:
  #     - ""
  #     resources:
  #     - pods
  #     verbs:
  #     - get
  #     - list
  #     - watch

# Additional ConfigMaps
configMap:
  enabled: false
  additionalLabels:
  # key: value
  annotations:
  # key: value
  files:
  # - nameSuffix: dev-config
  #   data:
  #     key1: value1
  #     key2: value2

# Additional Secrets
secret:
  enabled: false
  additionalLabels:
  # key: value
  annotations:
  # key: value
  files:
  # - nameSuffix: credentials
  #   data:
  #     secretKey1: secretValue1
  #     secretKey2: secretValue2
  # - nameSuffix: password
  #   data:
  #     secretKey1: secretValue1
  #     secretKey2: secretValue2
# Service Monitor to collect Prometheus metrices
serviceMonitor:
  enabled: false

  # Additional labels
  additionalLabels:
  # key: value

  # Additional annotations
  annotations:
  # key: value

  # List of the endpoints of service from which prometheus will scrape data
  endpoints:
    - interval: 10s
      path: /actuator/prometheus
      port: http

logging:
  enabled: false
  flows:
    # - name: "flow-name"
    #   globalOutputRefs:
    #     - paydart-output
    #   filters:
    #     - grep:
    #         regexp:
    #           - key: log
    #             pattern: /^\d{4}-\d{2}-\d{2}(.*)$/
    #     - tag_normaliser: {}
    #     - parser:
    #         remove_key_name_field: true
    #         reserve_data: true
    #         parse:
    #           type: regexp
    #           expression: >-
    #             /^(?<logTime>[^\s]*)\s\[(?<traceId>[^]]*)\]\s\[(?<spanId>[^]]*)\]\s(?<logLevel>[^\s]*)\s+\[(?<threadId>[^]]*)\]\s(?<className>[^:]*):\s(?<logMessage>(.*))$/
    - name: "flow-name2"
      localOutputRefs:
        - paydart-output
      filters:
        - stdout:
            output_type: json
        - tag_normaliser: {}
        - parser:
            parse:
              type: json
            remove_key_name_field: true
            reserve_data: true
        - record_modifier:
            remove_keys: "$.kubernetes.host,$.kubernetes.kubernetes_namespace,$.kubernetes.annotations,$.kubernetes.labels,$.kubernetes_namespace"

# autoscaling is used for horizonal pod autoscaling
autoscaling:
  # enabled is a boolean flag for enabling or disabling autoscaling
  enabled: true
  additionalLabels:
  annotations:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
      selectPolicy: Max

poddisruptionbudget:
  enabled: false # if you enable this, make sure your deployment creates atleast minAvailable+1 pods for no downtime deployment
  minAvailable: 1

application:
  enabled: false
  argocd_namespace: argocd-install-namespace
  deployment_namespace: default
  repo_path: infra/kubernetes/charts
  repoURL: git@github.com:umairedu/onboarding-project.git
  branch: master
  helm:
    valueFiles:
      - production/values.yaml
      - secrets://production/values-enc.yaml
  syncPolicy: {}
  #    automated:
  #      prune: false
  #      selfHeal: true
  #    syncOptions:
  #      - CreateNamespace=true
  #      - Replace=true
  #      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
