secret:
    enabled: ENC[AES256_GCM,data:lAw1fg==,iv:DWp5loBHkkTSVXwkCg9/X34Mp2RqSbc8l/7AoO1Mgro=,tag:XmFW25h4K5ndYWKNoO3tMw==,type:bool]
    additionalLabels: null
    annotations: null
    files:
        - nameSuffix: ENC[AES256_GCM,data:lLmqsWwj,iv:xE10urOyMm9DSbBtwXzgfuluYqjxdsPcbYPOROkK9w8=,tag:MuWkAVpiAdAt/qoGjfLkdw==,type:str]
          data:
            env: ENC[AES256_GCM,data:kcCoM8M3pATPvHlhsyLVTgElSEEQ1dlYlBsiM2CJyyPwVSNerd6mC0UDfuilei4gQjIJEtNCVRcAfp+v4VVpLDyb3XbuvST9V2vmuoj+o+SW2OiiOAgqjTatcrObKFu+CQKyFfJHf/BNjQ1WYN0rnomt95tMrf5jsqcQE8hABMAwjH9kfZ7ciZ0b8gLRiYahmP6jMu+Y9gwAvbIpiLbCMlugVH5yVoqmQeYNb1bYZHGs64zdYDLq9MT8mfIKUGdgqiaQzB60G2uSs5weXb1GJIXdEDIuzPQxt/Ap1KHurQgNrt+MiMIAJS0O3YBAIxzHG5RXyXe75UChK3lTPJ9K25A5ST23nDfnZSwXfg/o2dgOLGh3XSeluA79+t2ae2Epdw+DR0QMjcvX0cpsAUTjJt0XCIXSQwD2Zi+D7uDmYnYbWW1td1m+elrMYZHRbNlPv3/PvIATN4PcHE+h8kJkPBBHCkNHYLWxiDzupBJbAI5EuQwWo4u8ItUyLrLsjQ6AIf8n7/a2smaSkJ6oaCWphtRkppOCePKTMOvTF1G1k1ZfRc2INDQPbY5PE38UW9QoEQJSonryaAO04U4d1rSkIa2dmGVHOEoK9qoH5IDO/of9ZsK6b098s/L8twpI+0xiYorkkRDBQ8tyNyL6QxJB4mOB2joc2+ZZ5LiFaGWnw/lzwxX+j9bDNGVVjXPxYDFOvGY+6HCDBGFu1g==,iv:00DpulGYIrmvexHz2pr8qwZb1jkjoDJQe/7zOkkvKDs=,tag:MX3ODIykd0Rq1ndXdY+IzQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-af1-uat-app-secrets
          created_at: "2026-03-13T12:08:34Z"
          enc: AQICAHgEJiafceW3D0va99MIn9sancffrAKAY84D33DCdRx32QFY4u5r8FWK7EXoyjCXEcGHAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQrRqhlObURRnSFdhAgEQgDsOA1egNOAZXwhi+bSu7WNV9+Zzw4AAoPJaCdxoFW/d+bfEAqdPxIUsbYEXFGjlt5tbMqttPmoYzFP1UA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-13T12:08:35Z"
    mac: ENC[AES256_GCM,data:hPdNK2yyZgwXnZWa9cdp0UtQrBajEHHC4ol9WOIEq549Wmgo8coSoKeh+ewMjWTMqqjKLjfch0omKzBmX7qPu7YGtQmw2Uj85PxNwUeMzZnuGT7nmtlH/hbA+u//PcFn+vDbV8oBR7bwkLCgOr8WZardnGpYBS5TPdW7YjyPwIs=,iv:nV6PT2XsVjH26qQjDSHesyJd8m27VcM6p3pVrV5QtfE=,tag:2VSw1Rr/0YMlKBgDnO35hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
